### ISSUE TITLE
Symfonisk Controller

### ISSUE THREAD

**Issue by atze09** [Kane610/appdaemon-apps#2]
I have problems Initializing the app with Appdeamon 4 in hassio.

`2020-01-28 06:24:44.930091 INFO AppDaemon: Terminating Symfonisk_Controller
2020-01-28 06:24:44.937578 INFO AppDaemon: Reloading Module: /config/appdaemon/apps/symfonisk_controller.py
2020-01-28 06:24:44.951831 INFO AppDaemon: Initializing app Symfonisk_Controller using class SymfoniskController from module symfonisk_controller
2020-01-28 06:24:44.960769 INFO Symfonisk_Controller: {'module': 'symfonisk_controller', 'class': 'SymfoniskController'}
2020-01-28 06:24:44.965225 WARNING Symfonisk_Controller: ------------------------------------------------------------
2020-01-28 06:24:44.967035 WARNING Symfonisk_Controller: Unexpected error running initialize() for Symfonisk_Controller
2020-01-28 06:24:44.968514 WARNING Symfonisk_Controller: ------------------------------------------------------------
2020-01-28 06:24:44.971692 WARNING Symfonisk_Controller: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 145, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/symfonisk_controller.py", line 26, in initialize
    self.remote = self.args["symfonisk_sound_controller_1"]
KeyError: 'symfonisk_sound_controller_1'
2020-01-28 06:24:44.973586 WARNING Symfonisk_Controller: ------------------------------------------------------------`

Thank you in advance

**Comment by atze09** [comment]
Apps.yaml config ist:

Symfonisk_Controller:
  module: symfonisk_controller
  class: SymfoniskController

**Comment by lellky** [comment]
You have forgotten to provide two parameters for the app. The config should be something like:
Symfonisk_Controller:
module: symfonisk_controller
class: SymfoniskController
remote: NAME_OF_YOUR_REMOTE
media_player: NAME_OF_YOUR_MEDIA_PLAYER

You can see the parameters needed for app initialising here: https://github.com/Kane610/appdaemon-apps/blob/master/symfonisk_controller.py#L26

**Comment by atze09** [comment]
> You have forgotten to provide two parameters for the app. The config should be something like:
> Symfonisk_Controller:
> module: symfonisk_controller
> class: SymfoniskController
> remote: NAME_OF_YOUR_REMOTE
> media_player: NAME_OF_YOUR_MEDIA_PLAYER
> 
> You can see the parameters needed for app initialising here: https://github.com/Kane610/appdaemon-apps/blob/master/symfonisk_controller.py#L26

remote: symfonisk_sound_controller_1
media_player: media_player_wohnzimmer

This config gives me the initialize failure.

**Comment by lellky** [comment]
Yes, but you have also modified the file symfonisk_controller.py, this should not be done.

Change `self.args["symfonisk_sound_controller_1"]` to `self.args["remote"]` on line 26.

Se the file: https://github.com/Kane610/appdaemon-apps/blob/master/symfonisk_controller.py#L26

Also make sure you did not change line 27 as well.

**Comment by atze09** [comment]
> Yes, but you have also modified the file symfonisk_controller.py, this should not be done.
> 
> Change `self.args["symfonisk_sound_controller_1"]` to `self.args["remote"]` on line 26.
> 
> Se the file: https://github.com/Kane610/appdaemon-apps/blob/master/symfonisk_controller.py#L26
> 
> Also make sure you did not change line 27 as well.

Thank you very much for this hint. You solved my Problem. It was dumb from my Side..

**Comment by lellky** [comment]
You are welcome! Happy you got it fixed.
